version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "
      ls
      && npm install
      && npm run start:dev
      "
    volumes:
      - .:/code
    ports:
      - "8080:3000"
    env_file:
      - ./.env