version: "3.9"

services:
  web:
    build: .
      #&& npm install
    command: >
      sh -c "
      ls
      && npm run start:prod
      "
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./.env
